// Generated by https://quicktype.io
//Tipado de la respuesta de la API de pokemon con Paste Code as JSON
export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
